<?php
/**
 * @file
 * Provides tokens for taxa, names, references, etc.
 *
 * @copyright
 *   (C) 2021 EDIT
 *   European Distributed Institute of Taxonomy
 *   http://www.cybertaxonopmy.org
 *
 *   The contents of this module are subject to the Mozilla
 *   Public License Version 1.1.
 * @see http://www.mozilla.org/MPL/MPL-1.1.html
 *
 * @author
 *   - Andreas Kohlbecker <a.kohlbecker@BGBM.org>
 */

/**
 * Implements hook_token_info().
 */
function cdm_tokens_token_info() {
  $info = array();

  $info['tokens']['cdm']['taxon_name'] = t('The taxon name consisting of all name parts and sub species rank. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page)');
  $info['tokens']['cdm']['taxon_name:genus_or_uninomial'] = t('The taxon names uninomial or genus name. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page)');
  $info['tokens']['cdm']['taxon_name:family'] = t('The family name. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page)');
  $info['tokens']['cdm']['taxon_name:genus'] = t('The genus name. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page)');
  $info['tokens']['cdm']['taxon_name:infrageneric_epithet'] = t('The genus name. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page)');
  $info['tokens']['cdm']['taxon_name:epithet'] = t('The taxon names specific epithet. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page');
  $info['tokens']['cdm']['taxon_name:infraspecific_epithet'] = t('The taxon names specific epithet. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page');
  $info['tokens']['cdm']['taxon_name:reference'] = t('The taxon name nomenclatural reference. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page');
 // $info['tokens']['cdm']['taxon_name:reference:doi'] = t('The taxon name nomenclatural reference. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page');
  $info['tokens']['cdm']['taxon_name:authorship'] = t('The author(s) of taxon name. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page');
  $info['tokens']['cdm']['taxon_name:rank'] = t('The names rank. (Only present on a cdm_dataportal/taxon/ or cdm_dataportal/name/* page');

  return $info;
}

/**
 * Implements hook_tokens().
 */
function cdm_tokens_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $replacements = array();
  if ($type == 'cdm') {
    $token_values = _cdm_tokens_taxon_or_name();
    foreach ($tokens as $name => $original) {
      // Find the desired token by name
      switch ($name) {
        case 'taxon_name':
          if($token_values['taxon_name']){
            $replacements[$original] = $token_values['taxon_name'];
          }
          break;
        case 'taxon_name:genus_or_uninomial':
        case 'taxon_name:family':
        case 'taxon_name:genus':
        case 'taxon_name:infrageneric_epithet':
        case 'taxon_name:epithet':
        case 'taxon_name:infraspecific_epithet':
        case 'taxon_name:reference':
        case 'taxon_name:authorship':
        case 'taxon_name:rank':
          if($token_values[$name]){
            $replacements[$original] = $token_values[$name];
          }
          break;
      }
    }
  }

  // Return the replacements.
  return $replacements;
}


function _cdm_tokens_taxon_or_name(){
  static $current_token_values;
  if(!isset($current_token_values)){
    $current_token_values = [
      'taxon_name' => null,

      'taxon_name:genus_or_uninomial' => null,
      'taxon_name:family' => null,
      'taxon_name:genus' => null,
      'taxon_name:infrageneric_epithet' => null,
      'taxon_name:epithet' => null,
      'taxon_name:infraspecific_epithet' => null,
      'taxon_name:rank' => null,
      'taxon_name:reference' => null,
   //   'taxon_name:reference:doi' => null,
      'taxon_name:authorship' => null
    ];
    $taxon_name = null;

    $taxon_uuid = get_current_taxon_uuid();
    if($taxon_uuid){
      // this is request is made anyway. Practically we only query the L1 cache here.
      $taxon = cdm_ws_get(CDM_WS_PORTAL_TAXON, [$taxon_uuid]);
      if(isset_not_empty($taxon)){
        $taxon_name = $taxon->name;
      }
    } else {
     $name_uuid = get_current_name_uuid();
      $taxon_name = cdm_ws_get(CDM_WS_PORTAL_NAME, [$name_uuid]);
    }

    if(isset_not_empty($taxon_name)){
      $current_token_values['taxon_name'] = $taxon_name->nameCache;
      $current_token_values['taxon_name:family'] = $taxon_name->rank->isFamily & isset_not_empty($taxon_name->genusOrUninomial)? $taxon_name->genusOrUninomial : null;
      $current_token_values['taxon_name:genus_or_uninomial'] = isset_not_empty($taxon_name->genusOrUninomial) ?  $taxon_name->genusOrUninomial : NULL;
      $current_token_values['taxon_name:genus'] = !$taxon_name->rank->isSupraGeneric & isset_not_empty($taxon_name->genusOrUninomial) ? $taxon_name->genusOrUninomial : null;
      $current_token_values['taxon_name:infrageneric_epithet'] = $taxon_name->rank->isInfraGeneric & isset_not_empty($taxon_name->infraGenericEpithet) ? $taxon_name->infraGenericEpithet : null;
      $current_token_values['taxon_name:epithet'] = ( $taxon_name->rank->isSpecies || $taxon_name->rank->isInfraSpecific ) & isset_not_empty($taxon_name->specificEpithet) ? $taxon_name->specificEpithet : null;
      $current_token_values['taxon_name:infraspecific_epithet'] = $taxon_name->rank->isInfraSpecific & isset_not_empty($taxon_name->infraSpecificEpithet) ? $taxon_name->infraSpecificEpithet : null;
      if(@isset_not_empty($taxon_name->rank->representation_L10n)) {
        $current_token_values['taxon_name:rank'] = $taxon_name->rank->representation_L10n;
      }
      if(@isset_not_empty($taxon_name->nomenclaturalSource->citation->titleCache)) {
        $current_token_values['taxon_name:reference'] = $taxon_name->nomenclaturalSource->citation->titleCache;
      }
      if(@isset_not_empty($taxon_name->nomenclaturalSource->citation->authorship->titleCache)) {
        $current_token_values['taxon_name:authorship'] = $taxon_name->nomenclaturalSource->citation->authorship->titleCache;
      }
    }
  }

  return $current_token_values;
}

