<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: Fri, 02/15/2008 - 16:28
 * View: reviewz
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   reviewz, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $field_interfaces__data_standard_value -- 
 * $field_interfaces__data_standard_value_label -- The assigned label for $field_interfaces__data_standard_value
 * $field_review_value -- 
 * $field_review_value_label -- The assigned label for $field_review_value
 *
 * This function goes in your views-list-reviewz.tpl.php file
 */
 
 
 //now we add the stylesheet...
  drupal_add_css(path_to_theme() .'/views-list-reviewz.css');
  
  ?>
<div class="view-label view-field-title">
  <?php print $title_label ?>
</div>
<div class="view-field view-data-title">
  <?php print $title?>
</div>
<div class="view-field view-data-field-review-value">
  <?php print $field_review_value?>
</div>

<div class="view-label view-field-field-interfaces--data-standard-value">
  <?php print $field_interfaces__data_standard_value_label ?>
</div>
<div class="view-field view-data-field-interfaces--data-standard-value">
  <?php print $field_interfaces__data_standard_value?>
</div>




