<?php
/**
 * @file
 * This is a simple example of how a custom module can use webfm to list
 * files found in a specified directory
 */


/**
 * Implementation of hook_menu().
 */
function webfm_geoserver_menu(){
  $items = array();
  $items['webfm_geoserver_js'] = array(
    'title' => 'WebFM geoserver',
    'page callback' => 'webfm_geoserver_js',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/settings/webfm_geoserver'] = array(
    'title' => t('WebFM Geoserver Extension'),
    'description' => 'Configure the WebFM Geoserver Extension.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webfm_geoserver_settings'),
    'access arguments' => array('administer webfm'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Form to configure the WordPress standalone Audio Player.
 */
function webfm_geoserver_settings() {
 
  $form['webfm_geoserver_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('WebFM Geoserver Extension Settings'),
    '#description' => '<p>'.t('Config the Geoserver Extension Settings.').'</p>',
  );

  $form['webfm_geoserver_settings']['geoserver_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Geoserver URL'),
    '#default_value' => variable_get('geoserver_url', null),
    '#description' => t('The base url of the RESTful geoserver api.'),
  );
  $form['webfm_geoserver_settings']['geoserver_user'] = array(
    '#type' => 'textfield',
    '#title' => t('User Name'),
    '#default_value' => variable_get('geoserver_user', null),
    '#required' => TRUE
  );
  $form['webfm_geoserver_settings']['geoserver_password'] = array(
    '#type' => 'textfield',
    '#title' => t('Password'),
    '#default_value' => variable_get('geoserver_password', null),
    '#required' => TRUE
  );

//  $form['#validate'][]  = 'webfm_geoserver_settings_validate';
//  $form['#submit'][] = 'webfm_geoserver_settings_submit';

  return system_settings_form($form);
}

/**
 * Implementation of hook_webfm_extend_js().
 */
function webfm_geoserver_webfm_extend_js(){
  $modulepath = drupal_get_path('module', 'webfm_geoserver');
  drupal_add_js($modulepath. '/webfm_geoserver.js');
}


