<?php
/**
 * @file
 * Extensions to the cdm dataportal module specific for the Palmweb project
 *
 * @copyright
 *   (C) 2007-2013 EDIT
 *   European Distributed Institute of Taxonomy
 *   http://www.e-taxonomy.eu
 *
 *   The contents of this module are subject to the Mozilla
 *   Public License Version 1.1.
 * @see http://www.mozilla.org/MPL/MPL-1.1.html
 *
 * @author
 *   - Andreas Kohlbecker <a.kohlbecker@BGBM.org>
 *   - Alex Theys
 */


  /**
   * Implements hook_cdm_feature_node_blocks_alter()
   *
   */
  function palmweb_cdm_feature_node_blocks_alter(&$block_list, $taxon){

    if($taxon) {
      // taxon is only given if called from within the taxon general page part
      $numberOfChildren = count(cdm_ws_get(CDM_WS_PORTAL_TAXONOMY_CHILDNODES_OF_TAXON, array (get_taxonomictree_uuid_selected(), $taxon->uuid)));
      $subRank = 'sub taxa';
      if ($taxon->name->rank->titleCache == "Genus") {
        $subRank = "species";
      } else if ($taxon->name->rank->titleCache == "Species") {
        if($numberOfChildren==1){
          $subRank = "infraspecific taxon";
        }
        else {
          $subRank = "infraspecific taxa";
        }
      }
      if ($numberOfChildren > 0) {
        $block = feature_block('Number of Taxa');
        // FIXME use compose_cdm_feature_block_elements() in next line
        $block->content = array(markup_to_render_array('<ul class="feature-block-elements"><li>' . $numberOfChildren . " " . $subRank . '</li></ul>'));
        array_unshift($block_list, $block);
        cdm_toc_list_add_item('Number of Taxa', 'number-of-taxa', NULL, TRUE);
      }
    }

    return $block_list;
  }
