<?php
/**
 * @file
 * Extensions to the cdm dataportal module specific for the Palmweb project
 *
 * @copyright
 *   (C) 2007-2013 EDIT
 *   European Distributed Institute of Taxonomy
 *   http://www.e-taxonomy.eu
 *
 *   The contents of this module are subject to the Mozilla
 *   Public License Version 1.1.
 * @see http://www.mozilla.org/MPL/MPL-1.1.html
 *
 * @author
 *   - Andreas Kohlbecker <a.kohlbecker@BGBM.org>
 *   - Alex Theys
 */


  /**
   * Implements hook_cdm_feature_node_toc_items_alter()
   *
   * FIXME hook_cdm_feature_node_toc_items_alter() no longer exists, use cdm_toc_list_add_item() instead
   */
  function palmweb_cdm_feature_node_toc_items_alter($items){

    $http_request_params = drupal_get_query_parameters();
    $countFeatures = count($items);

    // number of taxa
    $numberOfChildren = count(cdm_ws_get(CDM_WS_PORTAL_TAXONOMY_CHILDNODES_OF_TAXON, array (
        get_taxonomictree_uuid_selected(),
        substr(strrchr($_GET["q"],'/'), 1),
    )));
    if ($numberOfChildren != 0) {
      array_unshift($items,
        l(
          t(theme('cdm_feature_name', array('feature_name' => 'Number of Taxa'))),
          $_GET['q'],
          array(
            'query' => $http_request_params,
            'attributes' => array('class' => array('toc')),
            'fragment' => generalizeString('Number Of Taxa'),
          )
        )
      );
    }

    // Setting the Anchor to the Bibliography section if the option is enabled.
    $show_bibliography = variable_get('cdm_show_bibliography', 1);

    $markerTypes['markerTypes'] = UUID_MARKERTYPE_USE;
    $useDescriptions = cdm_ws_get(CDM_WS_PORTAL_TAXON_DESCRIPTIONS, substr(strrchr($_GET["q"], '/'), 1), queryString($markerTypes));
    if (!empty($useDescriptions)) {
      $items[] = l(
            t(theme('cdm_feature_name', array('feature_name' => 'Uses'))),
            $_GET['q'],
            array(
                'query' => $http_request_params,
                'attributes' => array('class' => array('toc')),
                'fragment' => 'userecords'
            )
          );
    }

    if ($show_bibliography && $countFeatures != 0) {
      $items[] = l(
            t(theme('cdm_feature_name', array('feature_name' => 'Bibliography'))),
            $_GET['q'],
            array(
                'query' => $http_request_params,
                'attributes' => array('class' => array('toc')),
                'fragment' => 'bibliography'
              )
            );
    }
    return $items;
  }