<?php
/**
 * @file
 * An optional media gallery for the CDM DataPortal based on the FSI viewer.
 *
 * @copyright
 *   (C) 2007-2012 EDIT
 *   European Distributed Institute of Taxonomy
 *   http://www.e-taxonomy.eu
 *
 *   The contents of this module are subject to the Mozilla
 *   Public License Version 1.1.
 * @see http://www.mozilla.org/MPL/MPL-1.1.html
 *
 * @author
 *   - Andreas Kohlbecker <a.kohlbecker@BGBM.org>
 *   - Wouter Addink <w.addink@eti.uva.nl> (migration from Drupal 5 to Drupal7)
 */

/*
 * @file An optional media gallery for the CDM DataPortal based on the FSI
 * viewer Copyright (C) 2011 EDIT European Distributed Institute of Taxonomy
 * http://www.e-taxonomy.eu The contents of this file are subject to the Mozilla
 * Public License Version 1.1 See http://www.mozilla.org/MPL/MPL-1.1.html for
 * the full license terms. Author:Andreas Kohlbecker
 */

/**
 * Display help and module information.
 *
 * @param string $path
 *   Which path of the site we're displaying help.
 * @param array $arg
 *   Array that holds the current path as would be returned from arg() function.
 *
 * @return string
 *   Help text for the path.
 */
function fsi_gallery_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/help#fsi_gallery':
      $output = '<p>' . t("An optional media gallery for the CDM DataPortal based on the FSI viewer") . '</p>';
      break;
  }
  return $output;
}

/**
 * Generate the HTML text for the ext_link login block.
 */
function fsi_gallery_admin($form, &$form_state) {
  $form['fsi_query'] = array(
    '#type' => 'textfield',
    '#title' => t('FSI Viewer query'),
    '#default_value' => variable_get('fsi_query', '{name}'),
    '#maxlength' => 255,
    '#required' => TRUE,
    '#description' => '<p>' . t("You must at least add {name}, to search images
       matching a specific taxon name. You also can add other search terms which
       can be combined with 'AND' or 'OR'.") . '<p></p>'
    . t('For a comprehensive documentation please refer to !link1 or to !link2.', array (
      '!link1' => l(t('NeptuneLabs FSI Manual.pdf'), 'http://erez-server.dyndns.org/erez/pdf/NeptuneLabs%20FSI%20Manual.pdf'),
      '!link2' => l(t('eRez Imaging Server 5 Advanced Configuration'), 'http://erez-server.dyndns.org/erez/html/Advanced%20Configuration.html'),
      )) . '</p>',
  );
  /*
   * not yet used $form['fsi_name_substitutions'] = array( '#type' =>
   * 'textarea', '#title' => t('Taxon name subtitution rules'), '#default_value'
   * => variable_get('fsi_name_substitutions', FALSE), '#description' => t("One
   * regex substitution rule per line") );
   */
  $form['fsi_caption'] = array(
    '#type' => 'textarea',
    '#title' => t('Gallery caption'),
    '#default_value' => variable_get('fsi_caption', FALSE),
    '#description' => t('Copyright statements or similar text can be entered here.'),
  );

  return system_settings_form($form);
}

/**
 * Implements hook_menu().
 */
function fsi_gallery_menu() {
  $items = array();

  $items['admin/config/cdm_dataportal/fsi_gallery'] = array(
    'title' => 'FSI Gallery',
    'description' => 'An optional media gallery for the CDM DataPortal based on the FSI viewer.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fsi_gallery_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'weight' =>40,
  );

  return $items;
}

/**
 * @todo document this function.
 */
function _showcase_query_name($taxon) {
  $taggedName = $taxon->name->taggedName;

  $nameArray = array();
  foreach ($taggedName as $taggedText) {
    if ($taggedText->type == 'name') {
      $nameArray[] = $taggedText->text;
    }
    if ($taggedText->type == 'rank') {
      $nameArray[] = substr($taggedText->text, 0, 1);
    }
  }

  return join("%5F", $nameArray);
}
/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function theme_fsi_gallery($variables) {
  $taxon = $variables['taxon'];
  $media = $variables['media'];
  $query = variable_get('fsi_query', "{name}");
  $query = str_replace("{name}", _showcase_query_name($taxon), $query);
  $out = '

<script type="text/javascript" src="http://media.bgbm.org/erez/js/fsiwriter.js"></script>

<script type="text/javascript">
<!--
  writeFlashCode( "http://media.bgbm.org/erez/fsi/fsi.swf?&cfg=showcase_presets/showcase_info.fsi&effects=%26quality%3D95&showcase_query=' . $query . '&skin=silver&showcase_labeltextheight=50&textbox_textfrom=IPTC_WP6&textbox_height=50&param_backgroundcolor=454343&publishwmode=opaque&showcase_hscroll=true&showcase_basecolor=454343&plugins=textbox,fullscreen",
    "http://media.bgbm.org/erez/erez?src=erez-private/flashrequired.svg&tmp=Large&quality=97&width=620&height=400",
    "width=620;height=400;bgcolor=454343;wmode=opaque");
// -->
</script>
<noscript>
  <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,65,0" width="470" height="400">
    <param name="movie" value="http://media.bgbm.org/erez/fsi/fsi.swf?&cfg=showcase_presets/showcase_info.fsi&effects=%26quality%3D95&showcase_query=' . $query . '&skin=silver&showcase_labeltextheight=50&textbox_textfrom=IPTC_WP6&textbox_height=50&param_backgroundcolor=454343&publishwmode=opaque&showcase_hscroll=true&showcase_basecolor=454343plugins=textbox,fullscreen"/>
    <param name="bgcolor" value="454343" />
    <param name="wmode" value="opaque" />
    <param name="allowscriptaccess" value="always" />
    <param name="allowfullscreen" value="true" />
    <param name="quality" value="high" />
    <embed src="http://media.bgbm.org/erez/fsi/fsi.swf?&cfg=showcase_presets/showcase_info.fsi&effects=%26quality%3D95&showcase_query=' . $query . '&skin=silver&showcase_labeltextheight=50&textbox_textfrom=IPTC_WP6&textbox_height=50&param_backgroundcolor=454343&publishwmode=opaque&showcase_hscroll=true&showcase_basecolor=454343plugins=PrintSave,textbox,fullscreen"
      width="620"
      height="400"
      bgcolor="454343"
      wmode="opaque"
      allowscriptaccess="always"
      allowfullscreen="true"
      quality="high"
      type="application/x-shockwave-flash"
      pluginspage="http://www.adobe.com/go/getflashplayer">
    </embed>
  </object>

</noscript>';

  if (variable_get('fsi_caption', FALSE)) {
    $out .= '<div id="fsi_caption">' . variable_get('fsi_caption', FALSE) . '</div>';
  }
  return $out;
}
/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function fsi_gallery_theme() {
  return array(
    'fsi_gallery' => array('variables' => array('taxon' => NULL, 'media' => NULL)),
  );
}
