<?php
/**
 * @file
 * Install, update and uninstall functions for CDM_DataPortal install profile.
 *
 * This profile performs the same actions as the CDM_Portal profile, but with 
 * some extra blocks enabled for testing.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function CDM_Portal_Testing_install() {
  include_once DRUPAL_ROOT . '/profiles/CDM_Portal/CDM_Portal.install';
  CDM_Portal_install();

  $default_theme = 'garland';
  // Enable Taxontree and Search Taxa blocks.
  $blocks = array(
    array(
      'module' => 'cdm_taxontree',
      'delta' => 'cdm_tree',
      'theme' => $default_theme,
      'status' => 1,
      'weight' => -8,
      'region' => 'sidebar_first',
      'pages' => '',
      'cache' => -1,
    ),
    array(
      'module' => 'cdm_dataportal',
      'delta' => '2',
      'theme' => $default_theme,
      'status' => 1,
      'weight' => -10,
      'region' => 'sidebar_first',
      'pages' => '',
      'cache' => -1,
  ));
  $query = db_insert('block')->fields(array('module', 'delta', 'theme', 'status', 'weight', 'region', 'pages', 'cache'));
  foreach ($blocks as $block) {
    $query->values($block);
  }
  $query->execute();

}
