<?php
/**
 * This is the expertsdb_address_mexico module for use with expertsdb_address.
 *
 * <p>This module simply adds support for Mexican States</p>
 *
 * @version $Id: expertsdb_address_mexico.module,v 1.3 2007/10/10 17:52:06 ricflomag Exp $;
 * @package CCK
 * @category CCK
 * @author ricflomag
 * @filesource
 * @license http://www.gnu.org/licenses/gpl.txt GNU_GENERAL_PUBLIC_LICENSE
 * @link none yet
 */

/**
 * Implementation of hook_help
 *
 * Display help and module information
 * @param string section which section of the site we're displaying help
 * @return help text for section
 */
function expertsdb_address_mexico_help($section='') {

  $output = '';

  switch ($section) {
    case "admin/help#expertsdb_address_mexico":
      $output = '<p>'.  t("Adds support for Mexican States to expertsdb_address."). '</p>';
      break;
  }

  return $output;
} // function expertsdb_address_mexico_help()



/**
 * Implementation of hook_validate_address_fields
 *
 * This hook is used by expertsdb_address and any supporting modules which add country-specific field validation.
 * The first argument is an array, passed in by reference in 'fieldname=>error string' pairs. The error string should remain empty
 * so long as there are no errors. If there is an error, the string should be replaced with an appropriate t-ified message. The
 * second argument is the country code of the address. The first thing an implementation of this hook should do is check to see if
 * the country code matches the country for which the module was made to support. If not, it should return immediately, without
 * modifying the $errors array. This will ensure that only the country which SHOULD validate, does the validation. The third argument
 * is the item containing the values of the form.
 */
function expertsdb_address_mexico_validate_address_fields(&$errors, $country_code, $item, $field_name) {
  if ($country_code != 'MX' && $country_code != 'Mexico'){
    return;
  }
  $val_locale = array('es_MX' => 'es_MX');
  $default_locale = setlocale(LC_ALL, 0);

  foreach ($val_locale as $key => $value) {
    $current_locale = expertsdb_address_setLocaleCP($value);
    if (($item['street1'] != '') && (!preg_match("/^[,\.\'\-[:alpha:]0-9\/\s]+$/", _expertsdb_address_mexico_remove_accents($item['street1'])))) {
      $errors['street1'] = t('(Mexico): Illegal value for %name\'s Street field. Only letters, numbers, \' and - are valid. No other special characters allowed.', array('%name' => $field_name));
    }
    if (($item['street2'] != '') && (!preg_match("/^[,\.\'\-[:alpha:]0-9\/\s]+$/", _expertsdb_address_mexico_remove_accents($item['street2'])))) {
      $errors['street2'] = t('(Mexico):Illegal value for %name\'s Street Continued field. Only letters, numbers, \' and - are valid. No other special characters allowed.', array('%name' => $field_name));
    }
    if (($item['apt'] != '') && (!preg_match("/^[,\.\'\-[:alpha:]0-9\/\s]+$/", _expertsdb_address_mexico_remove_accents($item['apt'])))) {
      $errors['apt'] = t('(Mexico):Illegal value for %name\'s Apt/Suite Number field. Only letters, numbers, \' and - are valid. No other special characters allowed.', array('%name' => $field_name));
    }
    if (($item['city'] != '') && (!preg_match("/^[,\.\'\-[:alpha:]\s]+$/", _expertsdb_address_mexico_remove_accents($item['city'])))) {
      $errors['city'] = t('(Mexico):Illegal value for %name\'s City field. Only letters, \' and - are valid. No numbers or other special characters allowed.', array('%name' => $field_name));
    }
    if (($item['zip'] != '') && (!preg_match("/^\s*[0-9]{5}\s*$/", $item['zip']))) {
      $errors['zip'] = t('(Mexico):Illegal value for %name\'s ZIP field.', array('%name' => $field_name));
    }
    if (($item['other'] != '') && (!preg_match("/^[,\.\'\-[:alpha:]0-9\s]+$/", _expertsdb_address_mexico_remove_accents($item['other'])))) {
      $errors['other'] = t('(Mexico):Illegal value for %name\'s Other field. Only letters, numbers, \' and - are valid. No other special characters allowed.', array('%name' => $field_name));
    }
  }
  setlocale(LC_ALL, $default_locale);
  return;
}

//*****************************************************************************
// Remove all accents from a string
function _expertsdb_address_mexico_remove_accents($str){
  $str = utf8_decode($str);
  return preg_replace('/&([a-zA-Z])(uml|acute|grave|circ|tilde);/','$1',htmlentities($str,ENT_NOQUOTES));
}
