/*
 SWFObject v2.3.20130521 <http://github.com/swfobject/swfobject>
    is released under the MIT License <http://www.opensource.org/licenses/mit-license.php>
*/
var swfobject=function(){function x(){if(!t&&document.getElementsByTagName("body")[0]){try{var a=f.createElement("span");a.style.display="none";var b=f.getElementsByTagName("body")[0].appendChild(a);b.parentNode.removeChild(b)}catch(c){return}t=!0;b=y.length;for(a=0;a<b;a++)y[a]()}}function N(a){t?a():y[y.length]=a}function V(){var a=f.getElementsByTagName("body")[0],b=f.createElement("object");b.setAttribute("style","visibility: hidden;");b.setAttribute("type","application/x-shockwave-flash");var c=
a.appendChild(b);if(c){var e=0;(function h(){if("undefined"!==typeof c.GetVariable)try{var f=c.GetVariable("$version");f&&(f=f.split(" ")[1].split(","),g.pv=[parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10)])}catch(W){g.pv=[8,0,0]}else if(10>e){e++;setTimeout(h,10);return}a.removeChild(b);c=null;E()})()}else E()}function E(){var a=n.length;if(0<a)for(var b=0;b<a;b++){var c=n[b].id,e=n[b].callbackFn,d={success:!1,id:c};if(0<g.pv[0]){var h=u(c);if(h)if(!F(n[b].swfVersion)||g.wk&&312>g.wk)if(n[b].expressInstall&&
O()){d={};d.data=n[b].expressInstall;d.width=h.getAttribute("width")||"0";d.height=h.getAttribute("height")||"0";h.getAttribute("class")&&(d.styleclass=h.getAttribute("class"));h.getAttribute("align")&&(d.align=h.getAttribute("align"));var k={};h=h.getElementsByTagName("param");for(var l=h.length,p=0;p<l;p++)"movie"!==h[p].getAttribute("name").toLowerCase()&&(k[h[p].getAttribute("name")]=h[p].getAttribute("value"));P(d,k,c,e)}else c=h,g.ie&&4!=c.readyState?(c.style.display="none",k=f.createElement("div"),
c.parentNode.insertBefore(k,c),k.parentNode.replaceChild(G(c),k),A(c)):c.parentNode.replaceChild(G(c),c),e&&e(d);else v(c,!0),e&&(d.success=!0,d.ref=H(c),d.id=c,e(d))}else v(c,!0),e&&((c=H(c))&&"undefined"!==typeof c.SetVariable&&(d.success=!0,d.ref=c,d.id=c.id),e(d))}}function H(a){var b=null;(a=u(a))&&"OBJECT"===a.nodeName.toUpperCase()&&(b="undefined"!==typeof a.SetVariable?a:a.getElementsByTagName("object")[0]||a);return b}function O(){return!B&&F("6.0.65")&&(g.win||g.mac)&&!(g.wk&&312>g.wk)}
function P(a,b,c,e){var d=u(c);c=I(c);B=!0;J=e||null;Q={success:!1,id:c};if(d){"OBJECT"===d.nodeName.toUpperCase()?(z=G(d),C=null):(z=d,C=c);a.id="SWFObjectExprInst";if("undefined"===typeof a.width||!/%$/.test(a.width)&&310>parseInt(a.width,10))a.width="310";if("undefined"===typeof a.height||!/%$/.test(a.height)&&137>parseInt(a.height,10))a.height="137";e=g.ie?"ActiveX":"PlugIn";e="MMredirectURL="+encodeURIComponent(l.location.toString().replace(/&/g,"%26"))+"&MMplayerType="+e+"&MMdoctitle="+encodeURIComponent(f.title.slice(0,
47)+" - Flash Player Installation");b.flashvars="undefined"!==typeof b.flashvars?b.flashvars+("&"+e):e;g.ie&&4!=d.readyState&&(e=f.createElement("div"),c+="SWFObjectNew",e.setAttribute("id",c),d.parentNode.insertBefore(e,d),d.style.display="none",A(d));K(a,b,c)}}function G(a){var b=f.createElement("div");if(g.win&&g.ie)b.innerHTML=a.innerHTML;else if(a=a.getElementsByTagName("object")[0])if(a=a.childNodes)for(var c=a.length,e=0;e<c;e++)1==a[e].nodeType&&"PARAM"===a[e].nodeName||8==a[e].nodeType||
b.appendChild(a[e].cloneNode(!0));return b}function K(a,b,c){var e=u(c);c=I(c);if(g.wk&&312>g.wk)return d;if(e){var d=g.ie?f.createElement("div"):f.createElement("object");var h;"undefined"===typeof a.id&&(a.id=c);for(q in b)if(b.hasOwnProperty(q)&&"movie"!==q.toLowerCase()){c=d;var k=q,l=b[q],p=f.createElement("param");p.setAttribute("name",k);p.setAttribute("value",l);c.appendChild(p)}if(g.ie){b=a.data;d=d.innerHTML;var q=f.createElement("div");q.innerHTML="<object classid='clsid:D27CDB6E-AE6D-11cf-96B8-444553540000'><param name='movie' value='"+
b+"'>"+d+"</object>";d=q.firstChild}for(h in a)a.hasOwnProperty(h)&&(b=h.toLowerCase(),"styleclass"===b?d.setAttribute("class",a[h]):"classid"!==b&&"data"!==b&&d.setAttribute(h,a[h]));g.ie?D[D.length]=a.id:(d.setAttribute("type","application/x-shockwave-flash"),d.setAttribute("data",a.data));e.parentNode.replaceChild(d,e)}return d}function A(a){var b=u(a);b&&"OBJECT"===b.nodeName.toUpperCase()&&(g.ie?(b.style.display="none",function e(){if(4==b.readyState){for(var a in b)"function"===typeof b[a]&&
(b[a]=null);b.parentNode.removeChild(b)}else setTimeout(e,10)}()):b.parentNode.removeChild(b))}function I(a){return a&&a.nodeType&&1===a.nodeType?a.id:a}function u(a){if(a&&a.nodeType&&1===a.nodeType)return a;var b=null;try{b=f.getElementById(a)}catch(c){}return b}function X(a,b,c){a.attachEvent(b,c);w[w.length]=[a,b,c]}function F(a){var b=g.pv;a=(a+"").split(".");a[0]=parseInt(a[0],10);a[1]=parseInt(a[1],10)||0;a[2]=parseInt(a[2],10)||0;return b[0]>a[0]||b[0]==a[0]&&b[1]>a[1]||b[0]==a[0]&&b[1]==
a[1]&&b[2]>=a[2]?!0:!1}function R(a,b,c,e){var d=f.getElementsByTagName("head")[0];d&&(c="string"===typeof c?c:"screen",e&&(L=r=null),r&&L==c||(e=f.createElement("style"),e.setAttribute("type","text/css"),e.setAttribute("media",c),r=d.appendChild(e),g.ie&&"undefined"!==typeof f.styleSheets&&0<f.styleSheets.length&&(r=f.styleSheets[f.styleSheets.length-1]),L=c),r&&("undefined"!==typeof r.addRule?r.addRule(a,b):"undefined"!==typeof f.createTextNode&&r.appendChild(f.createTextNode(a+" {"+b+"}"))))}function v(a,
b){if(S){var c=b?"visible":"hidden",e=u(a);t&&e?e.style.visibility=c:"string"===typeof a&&R("#"+a,"visibility:"+c)}}function T(a){return null!==/[\\\"<>\.;]/.exec(a)&&"undefined"!==typeof encodeURIComponent?encodeURIComponent(a):a}var l=window,f=document,m=navigator,U=!1,y=[],n=[],D=[],w=[],z,C,J,Q,t=!1,B=!1,r,L,S=!0,M=!1,g=function(){var a="undefined"!==typeof f.getElementById&&"undefined"!==typeof f.getElementsByTagName&&"undefined"!==typeof f.createElement,b=m.userAgent.toLowerCase(),c=m.platform.toLowerCase(),
e=c?/win/.test(c):/win/.test(b);c=c?/mac/.test(c):/mac/.test(b);b=/webkit/.test(b)?parseFloat(b.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1;var d="Microsoft Internet Explorer"===m.appName,g=[0,0,0],k=null;if("undefined"!==typeof m.plugins&&"object"===typeof m.plugins["Shockwave Flash"])(k=m.plugins["Shockwave Flash"].description)&&"undefined"!==typeof m.mimeTypes&&m.mimeTypes["application/x-shockwave-flash"]&&m.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(U=!0,d=!1,k=k.replace(/^.*\s+(\S+\s+\S+$)/,
"$1"),g[0]=parseInt(k.replace(/^(.*)\..*$/,"$1"),10),g[1]=parseInt(k.replace(/^.*\.(.*)\s.*$/,"$1"),10),g[2]=/[a-zA-Z]/.test(k)?parseInt(k.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if("undefined"!==typeof l.ActiveXObject)try{if(k=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))d=!0,k=k.split(" ")[1].split(","),g=[parseInt(k[0],10),parseInt(k[1],10),parseInt(k[2],10)]}catch(W){}return{w3:a,pv:g,wk:b,ie:d,win:e,mac:c}}();(function(){g.w3&&(("undefined"!==typeof f.readyState&&
("complete"===f.readyState||"interactive"===f.readyState)||"undefined"===typeof f.readyState&&(f.getElementsByTagName("body")[0]||f.body))&&x(),t||("undefined"!==typeof f.addEventListener&&f.addEventListener("DOMContentLoaded",x,!1),g.ie&&(f.attachEvent("onreadystatechange",function b(){"complete"===f.readyState&&(f.detachEvent("onreadystatechange",b),x())}),l==top&&function c(){if(!t){try{f.documentElement.doScroll("left")}catch(e){setTimeout(c,0);return}x()}}()),g.wk&&function b(){t||(/loaded|complete/.test(f.readyState)?
x():setTimeout(b,0))}()))})();y[0]=function(){U?V():E()};(function(){g.ie&&window.attachEvent("onunload",function(){for(var a=w.length,b=0;b<a;b++)w[b][0].detachEvent(w[b][1],w[b][2]);a=D.length;for(b=0;b<a;b++)A(D[b]);for(var c in g)g[c]=null;g=null;for(var e in swfobject)swfobject[e]=null;swfobject=null})})();return{registerObject:function(a,b,c,e){if(g.w3&&a&&b){var d={};d.id=a;d.swfVersion=b;d.expressInstall=c;d.callbackFn=e;n[n.length]=d;v(a,!1)}else e&&e({success:!1,id:a})},getObjectById:function(a){if(g.w3)return H(a)},
embedSWF:function(a,b,c,e,d,f,k,l,p,q){var h=I(b),m={success:!1,id:h};g.w3&&!(g.wk&&312>g.wk)&&a&&b&&c&&e&&d?(v(h,!1),N(function(){c+="";e+="";var d={};if(p&&"object"===typeof p)for(var f in p)d[f]=p[f];d.data=a;d.width=c;d.height=e;f={};if(l&&"object"===typeof l)for(var g in l)f[g]=l[g];if(k&&"object"===typeof k)for(var n in k)if(k.hasOwnProperty(n)){g=M?encodeURIComponent(n):n;var r=M?encodeURIComponent(k[n]):k[n];f.flashvars="undefined"!==typeof f.flashvars?f.flashvars+("&"+g+"="+r):g+"="+r}try{var t=
K(d,f,b);d.id==h&&v(h,!0);m.success=!0;m.ref=t;m.id=t.id}catch(Y){v(h,!0)}q&&q(m)})):q&&q(m)},switchOffAutoHideShow:function(){S=!1},enableUriEncoding:function(a){M="undefined"===typeof a?!0:a},ua:g,getFlashPlayerVersion:function(){return{major:g.pv[0],minor:g.pv[1],release:g.pv[2]}},hasFlashPlayerVersion:F,createSWF:function(a,b,c){if(g.w3)return K(a,b,c)},showExpressInstall:function(a,b,c,e){g.w3&&O()&&P(a,b,c,e)},removeSWF:function(a){g.w3&&A(a)},createCSS:function(a,b,c,e){g.w3&&R(a,b,c,e)},addDomLoadEvent:N,
addLoadEvent:function(a){if("undefined"!==typeof l.addEventListener)l.addEventListener("load",a,!1);else if("undefined"!==typeof f.addEventListener)f.addEventListener("load",a,!1);else if("undefined"!==typeof l.attachEvent)X(l,"onload",a);else if("function"===typeof l.onload){var b=l.onload;l.onload=function(){b();a()}}else l.onload=a},getQueryParamValue:function(a){var b=f.location.search||f.location.hash;if(b){/\?/.test(b)&&(b=b.split("?")[1]);if(!a)return T(b);b=b.split("&");for(var c=0;c<b.length;c++)if(b[c].substring(0,
b[c].indexOf("="))==a)return T(b[c].substring(b[c].indexOf("=")+1))}return""},expressInstallCallback:function(){if(B){var a=u("SWFObjectExprInst");a&&z&&(a.parentNode.replaceChild(z,a),C&&(v(C,!0),g.ie&&(z.style.display="block")),J&&J(Q));B=!1}},version:"2.3"}}();window.chrome&&(swfobject.ua.pv=[100,0,0]);